/*
 * File: app/store/MenuTreeStore.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.MenuTreeStore', {
    extend: 'Ext.data.TreeStore',

    requires: [
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'MenuTreeStore',
            root: {
                expanded: true,
                text: 'Server List',
                children: [
                    {
                        text: '<b>Dashboard</b>',
                        id: 'MENU_01',
                        leaf: true,
                        iconCls: 'no-icon',
                        cls: 'parent-node last-children'
                    },
                    {
                        text: '<b>Server Management</b>',
                        id: 'MENU_02',
                        expanded: true,
                        iconCls: 'no-icon',
                        cls: 'parent-node',
                        children: [
                            {
                                text: 'Instances1',
                                id: 'MENU_02_01',
                                leaf: true,
                                iconCls: 'no-icon'
                            },
                            {
                                text: 'Instances2',
                                id: 'MENU_02_02',
                                leaf: true,
                                iconCls: 'no-icon'
                            },
                            {
                                text: 'Instances3',
                                id: 'MENU_02_03',
                                leaf: true,
                                iconCls: 'no-icon',
                                cls: 'last-children'
                            }
                        ]
                    },
                    {
                        text: '<b>RHEV Manager</b>',
                        id: 'MENU_03',
                        expanded: true,
                        iconCls: 'no-icon',
                        cls: 'parent-node',
                        children: [
                            {
                                text: 'Virtual Machines',
                                id: 'MENU_03_01',
                                leaf: true,
                                iconCls: 'no-icon'
                            },
                            {
                                text: 'Templates',
                                id: 'MENU_03_02',
                                leaf: true,
                                iconCls: 'no-icon',
                                cls: 'last-children'
                            }
                        ]
                    },
                    {
                        text: '<b>Scaling</b>',
                        id: 'MENU_04',
                        expanded: true,
                        iconCls: 'no-icon',
                        cls: 'parent-node',
                        children: [
                            {
                                text: 'Auto Sacling',
                                id: 'MENU_04_01',
                                leaf: true,
                                iconCls: 'no-icon'
                            },
                            {
                                text: 'Load Balancers',
                                id: 'MENU_04_02',
                                leaf: true,
                                iconCls: 'no-icon',
                                cls: 'last-children'
                            }
                        ]
                    },
                    {
                        text: '<b>Etc</b>',
                        id: 'MENU_05',
                        expanded: true,
                        iconCls: 'no-icon',
                        cls: 'parent-node',
                        children: [
                            {
                                text: 'sub menu1',
                                id: 'MENU_05_01',
                                leaf: true,
                                iconCls: 'no-icon'
                            },
                            {
                                text: 'sub menu2',
                                id: 'MENU_05_02',
                                leaf: true,
                                iconCls: 'no-icon'
                            },
                            {
                                text: 'sub menu3',
                                id: 'MENU_05_03',
                                leaf: true,
                                iconCls: 'no-icon'
                            },
                            {
                                text: 'sub menu4',
                                id: 'MENU_05_04',
                                leaf: true,
                                iconCls: 'no-icon',
                                cls: 'last-children'
                            }
                        ]
                    },
                    {
                        text: '<b>System Configuration</b>',
                        id: 'MENU_99',
                        expanded: true,
                        iconCls: 'no-icon',
                        cls: 'parent-node',
                        children: [
                            {
                                text: 'Menu Management',
                                id: 'MENU_99_01',
                                leaf: true,
                                iconCls: 'no-icon'
                            },
                            {
                                text: 'Group Mamagement',
                                id: 'MENU_99_02',
                                leaf: true,
                                iconCls: 'no-icon'
                            },
                            {
                                text: 'User Management',
                                id: 'MENU_99_03',
                                leaf: true,
                                iconCls: 'no-icon',
                                cls: 'last-children'
                            }
                        ]
                    }
                ]
            },
            fields: [
                {
                    name: 'text'
                }
            ]
        }, cfg)]);
    }
});