/*
 * File: app/model/InstanceMonitoringModel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.InstanceMonitoringModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'FACTOR_001',
            type: 'int'
        },
        {
            name: 'FACTOR_002',
            type: 'int'
        },
        {
            name: 'FACTOR_004',
            type: 'int'
        },
        {
            name: 'FACTOR_005',
            type: 'int'
        },
        {
            name: 'FACTOR_006',
            type: 'string'
        },
        {
            name: 'regDt',
            type: 'string'
        },
        {
            name: 'DISK_1',
            type: 'int'
        },
        {
            name: 'DISK_2',
            type: 'int'
        },
        {
            name: 'DISK_3',
            type: 'int'
        },
        {
            name: 'DISK_4',
            type: 'int'
        },
        {
            name: 'DISK_5',
            type: 'int'
        },
        {
            name: 'DISK_6',
            type: 'int'
        },
        {
            name: 'DISK_7',
            type: 'int'
        },
        {
            name: 'DISK_8',
            type: 'int'
        },
        {
            name: 'DISK_9',
            type: 'int'
        },
        {
            name: 'DISK_10',
            type: 'int'
        }
    ]
});