/*
 * File: app/view/almContainer.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.almContainer', {
    extend: 'Ext.container.Container',
    alias: 'widget.almcontainer',

    requires: [
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Separator',
        'Ext.form.field.Text',
        'Ext.grid.RowNumberer',
        'Ext.grid.column.Action',
        'Ext.form.Label',
        'Ext.form.Panel',
        'Ext.form.field.Display',
        'Ext.toolbar.Spacer'
    ],

    height: 755,
    id: 'almContainer',
    itemId: 'almContainer',
    width: 1000,
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    region: 'center',
                    id: 'almTabPanel',
                    itemId: 'almTabPanel',
                    padding: '5 0 0 0',
                    style: 'background:#ffffff',
                    bodyPadding: '',
                    activeTab: 1,
                    plain: true,
                    layout: {
                        type: 'card',
                        deferredRender: false
                    },
                    items: [
                        {
                            xtype: 'panel',
                            id: 'almTabProjectPanel',
                            itemId: 'almTabProjectPanel',
                            layout: 'border',
                            title: 'Project',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    region: 'center',
                                    id: 'almProjectGrid',
                                    itemId: 'almProjectGrid',
                                    minHeight: 100,
                                    autoScroll: true,
                                    columnLines: true,
                                    forceFit: true,
                                    store: 'AlmProjectStore',
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            id: 'instancesToolbar4',
                                            itemId: 'instancesToolbar',
                                            width: 150,
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    handler: function(button, e) {
                                                        var wizardWindow = Ext.create("widget.AlmWizardWindow");
                                                        wizardWindow.show();

                                                        almConstants.me.goAlmWizardPanel(0);

                                                        Ext.getCmp("wizardSelectSpaceGrid").getStore().removeAll();
                                                        Ext.getCmp("wizardSelectUserGrid").getStore().removeAll();

                                                    },
                                                    cls: 'auth-write',
                                                    text: 'Project Wizard'
                                                },
                                                {
                                                    xtype: 'button',
                                                    handler: function(button, e) {
                                                        var almProjectWindow = Ext.create("widget.AlmProjectWindow");

                                                        almProjectWindow.show();

                                                        Ext.getCmp('projectDuplBtn').hide();
                                                    },
                                                    cls: 'auth-write',
                                                    text: 'Create New Project'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    id: 'searchProjectName',
                                                    itemId: 'searchProjectName',
                                                    fieldLabel: 'Filtering',
                                                    labelWidth: 60,
                                                    emptyText: 'Search Project Name'
                                                }
                                            ]
                                        }
                                    ],
                                    columns: [
                                        {
                                            xtype: 'rownumberer',
                                            width: 50
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            minWidth: 80,
                                            dataIndex: 'projectCode',
                                            text: 'Project ID'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            minWidth: 150,
                                            dataIndex: 'projectName',
                                            text: 'Project Name'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            minWidth: 300,
                                            dataIndex: 'projectDescription',
                                            text: 'Project Description'
                                        },
                                        {
                                            xtype: 'actioncolumn',
                                            text: 'Delete',
                                            maxWidth: 60,
                                            minWidth: 70,
                                            style: 'text-align:left;',
                                            width: 60,
                                            defaultWidth: 60,
                                            align: 'center',
                                            hideable: false,
                                            menuText: '',
                                            items: [
                                                {
                                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                                        alert('delete');
                                                    },
                                                    icon: 'resources/images/icons/delete.png',
                                                    iconCls: ''
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    region: 'south',
                                    split: true,
                                    height: 150,
                                    id: 'almProjectDetailPanel',
                                    itemId: 'almProjectDetailPanel',
                                    autoScroll: true,
                                    layout: 'card',
                                    items: [
                                        {
                                            xtype: 'panel',
                                            height: 1000,
                                            id: 'blankPanel6',
                                            itemId: 'blankPanel',
                                            width: 1000
                                        },
                                        {
                                            xtype: 'panel',
                                            autoScroll: true,
                                            items: [
                                                {
                                                    xtype: 'tabpanel',
                                                    id: 'projectTabPanel',
                                                    itemId: 'projectTabPanel',
                                                    padding: '5 0 0 0',
                                                    style: 'background-color:#ffffff;',
                                                    activeTab: 0,
                                                    plain: true,
                                                    items: [
                                                        {
                                                            xtype: 'panel',
                                                            title: 'Summary',
                                                            dockedItems: [
                                                                {
                                                                    xtype: 'toolbar',
                                                                    dock: 'top',
                                                                    items: [
                                                                        {
                                                                            xtype: 'label',
                                                                            html: '<h2></h2>',
                                                                            id: 'almProjectTitleLabel',
                                                                            itemId: 'almProjectTitleLabel',
                                                                            margin: '',
                                                                            padding: '10 10 0 10',
                                                                            text: ''
                                                                        }
                                                                    ]
                                                                }
                                                            ],
                                                            items: [
                                                                {
                                                                    xtype: 'form',
                                                                    id: 'almProjectForm',
                                                                    itemId: 'almProjectForm',
                                                                    padding: '',
                                                                    defaults: {
                                                                        border: false,
                                                                        xtype: 'panel',
                                                                        flex: 1,
                                                                        layout: 'anchor'
                                                                    },
                                                                    bodyPadding: 10,
                                                                    bodyStyle: 'padding:5px 5px 0',
                                                                    header: false,
                                                                    fieldDefaults: {
                                                                        msgTarget: 'side',
                                                                        margin: '0 10',
                                                                        readOnly: true,
                                                                        labelStyle: 'font-weight: bold;',
                                                                        labelSeparator: ' :'
                                                                    },
                                                                    waitMsgTarget: 'instDescForm',
                                                                    items: [
                                                                        {
                                                                            xtype: 'displayfield',
                                                                            padding: 10,
                                                                            fieldLabel: 'Project ID',
                                                                            labelWidth: 140,
                                                                            name: 'projectCode'
                                                                        },
                                                                        {
                                                                            xtype: 'displayfield',
                                                                            padding: 10,
                                                                            fieldLabel: 'Project Name',
                                                                            labelWidth: 140,
                                                                            name: 'projectName'
                                                                        },
                                                                        {
                                                                            xtype: 'displayfield',
                                                                            padding: 10,
                                                                            fieldLabel: 'Project Description',
                                                                            labelWidth: 140,
                                                                            name: 'projectDescription'
                                                                        }
                                                                    ]
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'panel',
                                                            title: 'User',
                                                            items: [
                                                                {
                                                                    xtype: 'gridpanel',
                                                                    id: 'almProjectUserGrid',
                                                                    itemId: 'almProjectUserGrid',
                                                                    autoScroll: true,
                                                                    columnLines: true,
                                                                    forceFit: true,
                                                                    store: 'AlmProjectUsersStore',
                                                                    dockedItems: [
                                                                        {
                                                                            xtype: 'toolbar',
                                                                            dock: 'top',
                                                                            items: [
                                                                                {
                                                                                    xtype: 'tbspacer',
                                                                                    flex: 1
                                                                                },
                                                                                {
                                                                                    xtype: 'button',
                                                                                    handler: function(button, e) {
                                                                                        var almGroupUsersWindow = Ext.create("widget.AlmUsersWindow");

                                                                                        almGroupUsersWindow.show();

                                                                                        Ext.getCmp("addAlmUserType").setValue("project");

                                                                                        almConstants.me.searchPopAlmUser(true);
                                                                                    },
                                                                                    cls: 'auth-write',
                                                                                    text: 'Add Users to Project'
                                                                                }
                                                                            ]
                                                                        }
                                                                    ],
                                                                    columns: [
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            minWidth: 100,
                                                                            dataIndex: 'name',
                                                                            text: 'Name'
                                                                        },
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            minWidth: 150,
                                                                            dataIndex: 'displayName',
                                                                            text: 'Display Name'
                                                                        },
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            minWidth: 300,
                                                                            dataIndex: 'emailAddress',
                                                                            text: 'E-mail'
                                                                        },
                                                                        {
                                                                            xtype: 'actioncolumn',
                                                                            text: 'Delete',
                                                                            maxWidth: 60,
                                                                            minWidth: 70,
                                                                            style: 'text-align:left;',
                                                                            width: 60,
                                                                            defaultWidth: 60,
                                                                            align: 'center',
                                                                            hideable: false,
                                                                            menuText: '',
                                                                            items: [
                                                                                {
                                                                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                                                                        alert('delete');
                                                                                    },
                                                                                    icon: 'resources/images/icons/delete.png',
                                                                                    iconCls: ''
                                                                                }
                                                                            ]
                                                                        }
                                                                    ]
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'panel',
                                                            title: 'Confluence',
                                                            items: [
                                                                {
                                                                    xtype: 'gridpanel',
                                                                    id: 'almProjectConfluenceGrid',
                                                                    itemId: 'almProjectConfluenceGrid',
                                                                    autoScroll: true,
                                                                    columnLines: true,
                                                                    store: 'AlmProjectConfluencesStore',
                                                                    dockedItems: [
                                                                        {
                                                                            xtype: 'toolbar',
                                                                            dock: 'top',
                                                                            items: [
                                                                                {
                                                                                    xtype: 'tbspacer',
                                                                                    flex: 1
                                                                                },
                                                                                {
                                                                                    xtype: 'button',
                                                                                    handler: function(button, e) {
                                                                                        var almProjectSpaceWindow = Ext.create("widget.AlmProjectSpaceWindow");

                                                                                        almProjectSpaceWindow.show();

                                                                                        var grid = Ext.getCmp("almSpaceGrid").getStore().load();

                                                                                    },
                                                                                    cls: 'auth-write',
                                                                                    text: 'Add Space to Project'
                                                                                }
                                                                            ]
                                                                        }
                                                                    ],
                                                                    columns: [
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            width: 300,
                                                                            dataIndex: 'mappingCode',
                                                                            text: 'Space'
                                                                        },
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                                                if (value == 'COMPLETE') {
                                                                                    return '<span style="color:green;">' + value + '</span>';
                                                                                } else if (value == 'FAIL') {
                                                                                    return '<span style="color:red;">' + value + '</span>';
                                                                                }
                                                                                return value;
                                                                            },
                                                                            width: 100,
                                                                            dataIndex: 'status',
                                                                            text: 'Status'
                                                                        },
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            width: 120,
                                                                            dataIndex: 'exitCode',
                                                                            text: 'ErrorCode'
                                                                        },
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            width: 500,
                                                                            dataIndex: 'exitMessage',
                                                                            text: 'ErrorMessage'
                                                                        },
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            width: 180,
                                                                            dataIndex: 'lastUpdated',
                                                                            text: 'Last Updated'
                                                                        },
                                                                        {
                                                                            xtype: 'actioncolumn',
                                                                            text: 'Delete',
                                                                            style: 'text-align:left;',
                                                                            width: 60,
                                                                            align: 'center',
                                                                            hideable: false,
                                                                            menuText: '',
                                                                            items: [
                                                                                {
                                                                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                                                                        Ext.MessageBox.confirm('Confirm', '삭제 하시겠습니까?', function(btn){

                                                                                            if(btn == "yes"){

                                                                                                Ext.Ajax.request({
                                                                                                    url : GLOBAL.urlPrefix + "alm/project/"
                                                                                                    + almConstants.selectRow.get("projectCode") + "/confluence/" + record.get("mappingCode"),
                                                                                                    method: 'DELETE',
                                                                                                    headers: { 'Content-Type': 'application/json' },
                                                                                                    disableCaching : true,
                                                                                                    waitMsg: 'Delete Project confluence...',
                                                                                                    success: function(response){
                                                                                                        var msg = Ext.JSON.decode(response.responseText).msg;
                                                                                                        Ext.MessageBox.alert('알림', msg);

                                                                                                        Ext.getCmp("almProjectConfluenceGrid").getStore().reload();

                                                                                                    }
                                                                                                });
                                                                                            }

                                                                                        });

                                                                                    },
                                                                                    icon: 'resources/images/icons/delete.png',
                                                                                    iconCls: ''
                                                                                }
                                                                            ]
                                                                        }
                                                                    ]
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'panel',
                                                            title: 'Jenkins',
                                                            items: [
                                                                {
                                                                    xtype: 'gridpanel',
                                                                    id: 'almProjectJenkinsGrid',
                                                                    itemId: 'almProjectJenkinsGrid',
                                                                    autoScroll: true,
                                                                    columnLines: true,
                                                                    forceFit: false,
                                                                    store: 'AlmProjectJenkinsStore',
                                                                    dockedItems: [
                                                                        {
                                                                            xtype: 'toolbar',
                                                                            dock: 'top',
                                                                            items: [
                                                                                {
                                                                                    xtype: 'tbspacer',
                                                                                    flex: 1
                                                                                },
                                                                                {
                                                                                    xtype: 'button',
                                                                                    handler: function(button, e) {
                                                                                        var almProjectJobWindow = Ext.create("widget.AlmProjectJobWindow");

                                                                                        almProjectJobWindow.show();

                                                                                        Ext.getCmp("almJobGrid").getStore().load();

                                                                                    },
                                                                                    cls: 'auth-write',
                                                                                    text: 'Add Job to Project'
                                                                                }
                                                                            ]
                                                                        }
                                                                    ],
                                                                    columns: [
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            minWidth: 150,
                                                                            dataIndex: 'mappingCode',
                                                                            text: 'Job'
                                                                        },
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                                                if (value == 'COMPLETE') {
                                                                                    return '<span style="color:green;">' + value + '</span>';
                                                                                } else if (value == 'FAIL') {
                                                                                    return '<span style="color:red;">' + value + '</span>';
                                                                                }
                                                                                return value;
                                                                            },
                                                                            width: 100,
                                                                            dataIndex: 'status',
                                                                            text: 'Status'
                                                                        },
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            width: 120,
                                                                            dataIndex: 'exitCode',
                                                                            text: 'Error Code'
                                                                        },
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            width: 500,
                                                                            dataIndex: 'exitMessage',
                                                                            text: 'Error Message'
                                                                        },
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            width: 180,
                                                                            dataIndex: 'lastUpdated',
                                                                            text: 'Last Updated'
                                                                        },
                                                                        {
                                                                            xtype: 'actioncolumn',
                                                                            text: 'Delete',
                                                                            style: 'text-align:left;',
                                                                            width: 60,
                                                                            align: 'center',
                                                                            hideable: false,
                                                                            menuText: '',
                                                                            items: [
                                                                                {
                                                                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                                                                        Ext.MessageBox.confirm('Confirm', '삭제 하시겠습니까?', function(btn){

                                                                                            if(btn == "yes"){

                                                                                                Ext.Ajax.request({
                                                                                                    url : GLOBAL.urlPrefix + "alm/project/"
                                                                                                    + almConstants.selectRow.get("projectCode") + "/jenkins/" + record.get("mappingCode"),
                                                                                                    method: 'DELETE',
                                                                                                    headers: { 'Content-Type': 'application/json' },
                                                                                                    disableCaching : true,
                                                                                                    waitMsg: 'Delete Project Jenkins...',
                                                                                                    success: function(response){
                                                                                                        var msg = Ext.JSON.decode(response.responseText).msg;
                                                                                                        Ext.MessageBox.alert('알림', msg);

                                                                                                        Ext.getCmp("almProjectJenkinsGrid").getStore().reload();

                                                                                                    }
                                                                                                });
                                                                                            }

                                                                                        });

                                                                                    },
                                                                                    icon: 'resources/images/icons/delete.png',
                                                                                    iconCls: ''
                                                                                }
                                                                            ]
                                                                        }
                                                                    ]
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            id: 'almTabUserPanel',
                            itemId: 'almTabUserPanel',
                            layout: 'border',
                            title: 'User',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    region: 'center',
                                    id: 'almUserGrid',
                                    itemId: 'almUserGrid',
                                    minHeight: 100,
                                    autoScroll: true,
                                    columnLines: true,
                                    forceFit: true,
                                    store: 'AlmUserStore',
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            id: 'instancesToolbar2',
                                            itemId: 'instancesToolbar',
                                            width: 150,
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    handler: function(button, e) {
                                                        almConstants.me.showAlmUserWindow();
                                                    },
                                                    cls: 'auth-write',
                                                    text: 'Create New User'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    id: 'inputAlmUserName',
                                                    itemId: 'inputAlmUserName',
                                                    fieldLabel: 'Filtering',
                                                    labelWidth: 60,
                                                    emptyText: 'Search User ID',
                                                    enableKeyEvents: true
                                                },
                                                {
                                                    xtype: 'tbspacer',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'button',
                                                    handler: function(button, e) {
                                                        almConstants.me.searchAlmUser(false, 'left');
                                                    },
                                                    iconMask: false,
                                                    height: 30,
                                                    width: 25,
                                                    iconCls: 'x-toolbar-scroll-left'
                                                },
                                                {
                                                    xtype: 'button',
                                                    handler: function(button, e) {
                                                        almConstants.me.searchAlmUser(false, 'right');
                                                    },
                                                    iconMask: false,
                                                    height: 30,
                                                    width: 25,
                                                    iconCls: 'x-toolbar-scroll-right'
                                                }
                                            ]
                                        }
                                    ],
                                    columns: [
                                        {
                                            xtype: 'rownumberer',
                                            width: 40
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            minWidth: 100,
                                            dataIndex: 'userId',
                                            text: 'User ID'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            minWidth: 150,
                                            dataIndex: 'displayName',
                                            text: 'User Name'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            minWidth: 100,
                                            dataIndex: 'firstName',
                                            text: 'First Name'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            minWidth: 100,
                                            dataIndex: 'lastName',
                                            text: 'Last Name'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            minWidth: 300,
                                            dataIndex: 'emailAddress',
                                            text: 'Email'
                                        },
                                        {
                                            xtype: 'actioncolumn',
                                            text: 'Edit',
                                            maxWidth: 65,
                                            minWidth: 65,
                                            style: 'text-align:left;',
                                            width: 65,
                                            align: 'center',
                                            hideable: false,
                                            menuText: '',
                                            items: [
                                                {
                                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                                        almConstants.actionRow = record;
                                                        almConstants.me.showAlmUserWindow('edit');
                                                    },
                                                    icon: 'resources/images/icons/cog.png',
                                                    iconCls: ''
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'actioncolumn',
                                            text: 'Delete',
                                            maxWidth: 60,
                                            minWidth: 70,
                                            style: 'text-align:left;',
                                            width: 60,
                                            defaultWidth: 60,
                                            align: 'center',
                                            hideable: false,
                                            menuText: '',
                                            items: [
                                                {
                                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                                        almConstants.actionRow = record;
                                                        almConstants.me.deleteAlmUserWindow();
                                                    },
                                                    icon: 'resources/images/icons/delete.png',
                                                    iconCls: ''
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    region: 'south',
                                    split: true,
                                    height: 150,
                                    id: 'almUserDetailPanel',
                                    itemId: 'almUserDetailPanel',
                                    autoScroll: true,
                                    layout: 'card',
                                    items: [
                                        {
                                            xtype: 'panel',
                                            height: 1000,
                                            id: 'blankPanel5',
                                            itemId: 'blankPanel',
                                            width: 1000
                                        },
                                        {
                                            xtype: 'panel',
                                            autoScroll: true,
                                            items: [
                                                {
                                                    xtype: 'form',
                                                    id: 'almUserForm',
                                                    itemId: 'almUserForm',
                                                    padding: '',
                                                    defaults: {
                                                        border: false,
                                                        xtype: 'panel',
                                                        flex: 1,
                                                        layout: 'anchor'
                                                    },
                                                    bodyPadding: 10,
                                                    bodyStyle: 'padding:5px 5px 0',
                                                    header: false,
                                                    fieldDefaults: {
                                                        msgTarget: 'side',
                                                        margin: '0 10',
                                                        readOnly: true,
                                                        labelStyle: 'font-weight: bold;',
                                                        labelSeparator: ' :'
                                                    },
                                                    waitMsgTarget: 'instDescForm',
                                                    items: [
                                                        {
                                                            xtype: 'label',
                                                            html: '<h2></h2>',
                                                            id: 'almUserTitleLabel',
                                                            itemId: 'almUserTitleLabel',
                                                            padding: 1
                                                        },
                                                        {
                                                            xtype: 'displayfield',
                                                            padding: 10,
                                                            fieldLabel: 'User ID',
                                                            name: 'name'
                                                        },
                                                        {
                                                            xtype: 'displayfield',
                                                            padding: 10,
                                                            fieldLabel: 'User Name',
                                                            name: 'displayName'
                                                        },
                                                        {
                                                            xtype: 'displayfield',
                                                            padding: 10,
                                                            fieldLabel: 'First Name',
                                                            name: 'firstName'
                                                        },
                                                        {
                                                            xtype: 'displayfield',
                                                            padding: 10,
                                                            fieldLabel: 'Last Name',
                                                            name: 'lastName'
                                                        },
                                                        {
                                                            xtype: 'displayfield',
                                                            padding: 10,
                                                            fieldLabel: 'Email',
                                                            name: 'emailAddress'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            id: 'almTabGroupPanel',
                            itemId: 'almTabGroupPanel',
                            layout: 'border',
                            title: 'Group',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    region: 'center',
                                    id: 'almGroupGrid',
                                    itemId: 'almGroupGrid',
                                    minHeight: 100,
                                    autoScroll: true,
                                    columnLines: true,
                                    forceFit: true,
                                    store: 'AlmGroupStore',
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            id: 'instancesToolbar3',
                                            itemId: 'instancesToolbar',
                                            width: 150,
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    handler: function(button, e) {
                                                        almConstants.me.showAlmGroupWindow();
                                                    },
                                                    cls: 'auth-write',
                                                    id: 'createUserBtn2',
                                                    itemId: 'createUserBtn',
                                                    text: 'Create New Group'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    id: 'inputAlmGroupName',
                                                    itemId: 'inputAlmGroupName',
                                                    fieldLabel: 'Filtering',
                                                    labelWidth: 60,
                                                    emptyText: 'Search Group Name',
                                                    enableKeyEvents: true
                                                },
                                                {
                                                    xtype: 'tbspacer',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'button',
                                                    handler: function(button, e) {
                                                        almConstants.me.searchAlmGroup(false, 'left');
                                                    },
                                                    iconMask: false,
                                                    height: 30,
                                                    width: 25,
                                                    iconCls: 'x-toolbar-scroll-left'
                                                },
                                                {
                                                    xtype: 'button',
                                                    handler: function(button, e) {
                                                        almConstants.me.searchAlmGroup(false, 'right');
                                                    },
                                                    iconMask: false,
                                                    height: 30,
                                                    width: 25,
                                                    iconCls: 'x-toolbar-scroll-right'
                                                }
                                            ]
                                        }
                                    ],
                                    columns: [
                                        {
                                            xtype: 'rownumberer',
                                            width: 60,
                                            defaultWidth: 60
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            minWidth: 150,
                                            dataIndex: 'name',
                                            text: 'Group Name'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            minWidth: 100,
                                            dataIndex: 'active',
                                            text: 'Active'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            minWidth: 400,
                                            dataIndex: 'description',
                                            text: 'Description'
                                        },
                                        {
                                            xtype: 'actioncolumn',
                                            text: 'Delete',
                                            maxWidth: 60,
                                            minWidth: 70,
                                            style: 'text-align:left;',
                                            width: 60,
                                            defaultWidth: 60,
                                            align: 'center',
                                            hideable: false,
                                            menuText: '',
                                            items: [
                                                {
                                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                                        Ext.MessageBox.confirm('Confirm', '삭제 하시겠습니까?', function(btn){

                                                            if(btn == "yes"){

                                                                Ext.Ajax.request({
                                                                    url : GLOBAL.urlPrefix + "alm/groupmanagement/" + record.get("name"),
                                                                    method: 'DELETE',
                                                                    headers: { 'Content-Type': 'application/json' },
                                                                    disableCaching : true,
                                                                    waitMsg: 'Delete ALM Group...',
                                                                    success: function(response){
                                                                        var msg = Ext.JSON.decode(response.responseText).msg;
                                                                        Ext.MessageBox.alert('알림', msg);

                                                                        Ext.getCmp("almGroupGrid").getStore().reload();
                                                                        Ext.getCmp("almGroupDetailPanel").layout.setActiveItem(0);

                                                                    }
                                                                });
                                                            }

                                                        });
                                                    },
                                                    icon: 'resources/images/icons/delete.png',
                                                    iconCls: ''
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    region: 'south',
                                    split: true,
                                    height: 150,
                                    id: 'almGroupDetailPanel',
                                    itemId: 'almGroupDetailPanel',
                                    autoScroll: true,
                                    layout: 'card',
                                    items: [
                                        {
                                            xtype: 'panel',
                                            height: 1000,
                                            id: 'blankPanel7',
                                            itemId: 'blankPanel1',
                                            width: 1000
                                        },
                                        {
                                            xtype: 'panel',
                                            autoScroll: true,
                                            dockedItems: [
                                                {
                                                    xtype: 'label',
                                                    dock: 'top',
                                                    html: '<h2></h2>',
                                                    id: 'almGroupTitleLabel',
                                                    itemId: 'almGroupTitleLabel',
                                                    margin: '5 0 0 0',
                                                    padding: 2,
                                                    text: ''
                                                }
                                            ],
                                            items: [
                                                {
                                                    xtype: 'tabpanel',
                                                    id: 'almGroupTabPanel',
                                                    itemId: 'almGroupTabPanel',
                                                    margin: '',
                                                    padding: '15 10 10 10',
                                                    style: 'background:#ffffff',
                                                    bodyBorder: false,
                                                    bodyPadding: '',
                                                    activeTab: 0,
                                                    plain: true,
                                                    items: [
                                                        {
                                                            xtype: 'panel',
                                                            title: 'Summary',
                                                            items: [
                                                                {
                                                                    xtype: 'form',
                                                                    id: 'almGroupForm',
                                                                    itemId: 'almGroupForm',
                                                                    padding: '30 0 0 0',
                                                                    defaults: {
                                                                        border: false,
                                                                        xtype: 'panel',
                                                                        flex: 1,
                                                                        layout: 'anchor'
                                                                    },
                                                                    bodyPadding: 10,
                                                                    bodyStyle: 'padding:5px 5px 0',
                                                                    header: false,
                                                                    fieldDefaults: {
                                                                        msgTarget: 'side',
                                                                        margin: '0 10',
                                                                        readOnly: true,
                                                                        labelStyle: 'font-weight: bold;',
                                                                        labelSeparator: ' :'
                                                                    },
                                                                    waitMsgTarget: 'instDescForm',
                                                                    items: [
                                                                        {
                                                                            xtype: 'displayfield',
                                                                            padding: '10 10 10 10',
                                                                            width: 600,
                                                                            fieldLabel: 'Group Name',
                                                                            labelWidth: 150,
                                                                            name: 'name'
                                                                        },
                                                                        {
                                                                            xtype: 'displayfield',
                                                                            padding: '10 10 10 10',
                                                                            width: 600,
                                                                            fieldLabel: 'Active',
                                                                            labelWidth: 150,
                                                                            name: 'active'
                                                                        },
                                                                        {
                                                                            xtype: 'displayfield',
                                                                            padding: '10 10 10 10',
                                                                            width: 600,
                                                                            fieldLabel: 'Description',
                                                                            labelWidth: 150,
                                                                            name: 'description'
                                                                        }
                                                                    ]
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'panel',
                                                            title: 'Users',
                                                            items: [
                                                                {
                                                                    xtype: 'gridpanel',
                                                                    id: 'almGroupUserGrid',
                                                                    itemId: 'almGroupUserGrid',
                                                                    columnLines: true,
                                                                    forceFit: true,
                                                                    store: 'AlmGroupUsersStore',
                                                                    columns: [
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            minWidth: 100,
                                                                            dataIndex: 'name',
                                                                            text: 'Name'
                                                                        },
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            minWidth: 150,
                                                                            dataIndex: 'displayName',
                                                                            text: 'Display Name'
                                                                        },
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            minWidth: 300,
                                                                            dataIndex: 'emailAddress',
                                                                            text: 'E-mail'
                                                                        },
                                                                        {
                                                                            xtype: 'actioncolumn',
                                                                            text: 'Delete',
                                                                            maxWidth: 60,
                                                                            minWidth: 70,
                                                                            style: 'text-align:left;',
                                                                            width: 60,
                                                                            defaultWidth: 60,
                                                                            align: 'center',
                                                                            hideable: false,
                                                                            menuText: '',
                                                                            items: [
                                                                                {
                                                                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                                                                        Ext.MessageBox.confirm('Confirm', '삭제 하시겠습니까?', function(btn){

                                                                                            if(btn == "yes"){

                                                                                                Ext.Ajax.request({
                                                                                                    url : GLOBAL.urlPrefix + "alm/groupmanagement/"
                                                                                                    + almConstants.selectRow.get("name") + "/" + record.get("name"),
                                                                                                    method: 'DELETE',
                                                                                                    headers: { 'Content-Type': 'application/json' },
                                                                                                    disableCaching : true,
                                                                                                    waitMsg: 'Delete ALM Group User...',
                                                                                                    success: function(response){
                                                                                                        var msg = Ext.JSON.decode(response.responseText).msg;
                                                                                                        Ext.MessageBox.alert('알림', msg);

                                                                                                        Ext.getCmp("almGroupUserGrid").getStore().reload();

                                                                                                    }
                                                                                                });
                                                                                            }

                                                                                        });

                                                                                    },
                                                                                    icon: 'resources/images/icons/delete.png',
                                                                                    iconCls: ''
                                                                                }
                                                                            ]
                                                                        }
                                                                    ],
                                                                    dockedItems: [
                                                                        {
                                                                            xtype: 'toolbar',
                                                                            dock: 'top',
                                                                            items: [
                                                                                {
                                                                                    xtype: 'tbspacer',
                                                                                    flex: 1
                                                                                },
                                                                                {
                                                                                    xtype: 'button',
                                                                                    handler: function(button, e) {
                                                                                        var almGroupUsersWindow = Ext.create("widget.AlmUsersWindow");

                                                                                        almGroupUsersWindow.show();

                                                                                        Ext.getCmp("addAlmUserType").setValue("group");

                                                                                        almConstants.me.searchPopAlmUser(true);
                                                                                    },
                                                                                    cls: 'auth-write',
                                                                                    width: 150,
                                                                                    text: 'Add Users to Group'
                                                                                }
                                                                            ]
                                                                        }
                                                                    ]
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            id: 'almTabRepositoryPanel',
                            itemId: 'almTabRepositoryPanel',
                            layout: 'border',
                            title: 'Repository',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    region: 'center',
                                    id: 'almRepositoryGrid',
                                    itemId: 'almRepositoryGrid',
                                    minHeight: 100,
                                    autoScroll: true,
                                    columnLines: true,
                                    forceFit: true,
                                    store: 'AlmRepositoryStore',
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            width: 150,
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    handler: function(button, e) {
                                                        var repositoryWindow = Ext.create("widget.AlmRepositoryWindow");
                                                        repositoryWindow.show();

                                                    },
                                                    cls: 'auth-write',
                                                    text: 'Add Repository'
                                                },
                                                {
                                                    xtype: 'tbseparator',
                                                    cls: 'auth-write'
                                                }
                                            ]
                                        }
                                    ],
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            minWidth: 150,
                                            dataIndex: 'repositoryCode',
                                            text: 'Name'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                if(value == '10') {
                                                    return 'svn';
                                                } else if(value == '20') {
                                                    return 'git';
                                                } else {
                                                    return value;
                                                }
                                            },
                                            minWidth: 60,
                                            dataIndex: 'repositoryType',
                                            text: 'Type'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            minWidth: 250,
                                            dataIndex: 'repositoryDescription',
                                            text: 'Description'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            minWidth: 250,
                                            dataIndex: 'repositoryUrl',
                                            text: 'Url'
                                        },
                                        {
                                            xtype: 'actioncolumn',
                                            text: 'Delete',
                                            maxWidth: 60,
                                            minWidth: 70,
                                            style: 'text-align:left;',
                                            width: 60,
                                            defaultWidth: 60,
                                            align: 'center',
                                            hideable: false,
                                            menuText: '',
                                            items: [
                                                {
                                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                                        alert('delete');
                                                        /*
                                                        Ext.MessageBox.confirm('Confirm', '삭제 하시겠습니까?', function(btn){

                                                        if(btn == "yes"){

                                                        Ext.Ajax.request({
                                                        url : GLOBAL.urlPrefix + "alm/groupmanagement/" + record.get("name"),
                                                        method: 'DELETE',
                                                        headers: { 'Content-Type': 'application/json' },
                                                        disableCaching : true,
                                                        waitMsg: 'Delete ALM Group...',
                                                        success: function(response){
                                                        var msg = Ext.JSON.decode(response.responseText).msg;
                                                        Ext.MessageBox.alert('알림', msg);

                                                        Ext.getCmp("almGroupGrid").getStore().reload();
                                                        Ext.getCmp("almGroupDetailPanel").layout.setActiveItem(0);

                                                        }
                                                        });
                                                        }

                                                        });
                                                        */
                                                    },
                                                    icon: 'resources/images/icons/delete.png',
                                                    iconCls: ''
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    region: 'south',
                                    split: true,
                                    height: 150,
                                    id: 'almRepositoryDetailPanel',
                                    itemId: 'almRepositoryDetailPanel',
                                    autoScroll: true,
                                    layout: 'card',
                                    items: [
                                        {
                                            xtype: 'panel',
                                            height: 1000,
                                            id: 'blankPanel8',
                                            itemId: 'blankPanel1',
                                            width: 1000
                                        },
                                        {
                                            xtype: 'panel',
                                            autoScroll: true,
                                            items: [
                                                {
                                                    xtype: 'form',
                                                    id: 'almRepositoryForm',
                                                    itemId: 'almRepositoryForm',
                                                    padding: '',
                                                    defaults: {
                                                        border: false,
                                                        xtype: 'panel',
                                                        flex: 1,
                                                        layout: 'anchor'
                                                    },
                                                    bodyPadding: 10,
                                                    bodyStyle: 'padding:5px 5px 0',
                                                    header: false,
                                                    fieldDefaults: {
                                                        msgTarget: 'side',
                                                        margin: '0 10',
                                                        readOnly: true,
                                                        labelStyle: 'font-weight: bold;',
                                                        labelSeparator: ' :',
                                                        labelWidth: 160
                                                    },
                                                    waitMsgTarget: 'instDescForm',
                                                    items: [
                                                        {
                                                            xtype: 'label',
                                                            html: '<h2></h2>',
                                                            id: 'almRepositoryTitleLabel',
                                                            itemId: 'almRepositoryTitleLabel',
                                                            padding: 1
                                                        },
                                                        {
                                                            xtype: 'displayfield',
                                                            padding: 10,
                                                            fieldLabel: 'Repository Name',
                                                            name: 'repositoryCode'
                                                        },
                                                        {
                                                            xtype: 'displayfield',
                                                            renderer: function(value, displayField) {
                                                                if(value == '10') {
                                                                    return 'svn';
                                                                } else if(value == '20') {
                                                                    return 'git';
                                                                } else {
                                                                    return value;
                                                                }
                                                            },
                                                            padding: 10,
                                                            fieldLabel: 'Reposiroty Type',
                                                            name: 'repositoryType'
                                                        },
                                                        {
                                                            xtype: 'displayfield',
                                                            padding: 10,
                                                            fieldLabel: 'Repository Description',
                                                            name: 'repositoryDescription'
                                                        },
                                                        {
                                                            xtype: 'displayfield',
                                                            padding: 10,
                                                            fieldLabel: 'Repository URL',
                                                            name: 'repositoryUrl'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});