/*
 * File: app/view/clusterDevicePathWindow.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.clusterDevicePathWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.clusterDevicePathWindow',

    requires: [
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Text',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    height: 146,
    width: 400,
    resizable: false,
    layout: 'border',
    title: 'Osd Device Path',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'center',
                    id: 'clusterDevicePathTopPanel',
                    itemId: 'clusterDevicePathTopPanel',
                    items: [
                        {
                            xtype: 'form',
                            height: 156,
                            id: 'clusterDevicePathFormPanel',
                            itemId: 'clusterDevicePathFormPanel',
                            bodyPadding: 10,
                            items: [
                                {
                                    xtype: 'fieldset',
                                    padding: 10,
                                    title: '',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            id: 'osdDevicePath',
                                            itemId: 'osdDevicePath',
                                            fieldLabel: 'Path',
                                            labelAlign: 'right',
                                            labelWidth: 54,
                                            name: 'osdDevicePath',
                                            allowBlank: false,
                                            allowOnlyWhitespace: false,
                                            enforceMaxLength: true,
                                            maskRe: /[a-zA-Z0-9_\-\/\.]/,
                                            maxLength: 80
                                        }
                                    ]
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            id: 'createBucketToolbar2',
                            itemId: 'createBucketToolbar',
                            layout: {
                                type: 'hbox',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        storageConstants.me.addOsdDevicePath();

                                    },
                                    padding: '2 20 2 20',
                                    text: 'Ok'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        var myForm = Ext.getCmp("clusterDevicePathFormPanel");

                                        myForm.getForm().findField("osdDevicePath").setValue('');


                                    },
                                    padding: '2 12 2 12',
                                    text: 'Clear'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});