/*
 * File: app/view/EditInstanceWindow.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.EditInstanceWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.EditInstanceWindow',

    requires: [
        'Ext.form.Panel',
        'Ext.XTemplate',
        'Ext.form.field.Hidden',
        'Ext.form.FieldSet',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.File',
        'Ext.form.field.Display',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    height: 530,
    id: 'EditInstanceWindow',
    itemId: 'EditInstanceWindow',
    width: 450,
    resizable: false,
    layout: 'border',
    title: 'Edit Instance',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    flex: 1,
                    region: 'center',
                    header: false,
                    title: 'instanceNamePanel',
                    items: [
                        {
                            xtype: 'form',
                            id: 'editInstanceForm',
                            itemId: 'editInstanceForm',
                            bodyPadding: 15,
                            fieldDefaults: {
                                msgTarget: 'side',
                                labelWidth: 120
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    afterLabelTextTpl: [
                                        '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                                    ],
                                    fieldLabel: 'Name',
                                    labelWidth: 120,
                                    name: 'displayName',
                                    allowBlank: false,
                                    vtype: 'template'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    anchor: '100%',
                                    fieldLabel: 'Label',
                                    name: 'machineId'
                                },
                                {
                                    xtype: 'fieldset',
                                    margin: '20 0 10 0',
                                    title: 'SSH Settings (Optional)',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'SSH Port',
                                            labelWidth: 130,
                                            name: 'sshPort',
                                            vtype: 'numeric'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Username',
                                            labelWidth: 130,
                                            name: 'sshUsername',
                                            vtype: 'numeric'
                                        },
                                        {
                                            xtype: 'radiogroup',
                                            padding: '0 0 0 135',
                                            items: [
                                                {
                                                    xtype: 'radiofield',
                                                    boxLabel: 'Use Passowrd',
                                                    checked: true,
                                                    listeners: {
                                                        change: {
                                                            fn: me.onRadiofieldChange,
                                                            scope: me
                                                        }
                                                    }
                                                },
                                                {
                                                    xtype: 'radiofield',
                                                    boxLabel: ' Use Key'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Password',
                                            labelWidth: 130,
                                            name: 'sshPassword',
                                            vtype: 'numeric'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Password Confirm',
                                            labelWidth: 130,
                                            name: 'confirmSshPassword',
                                            vtype: 'numeric'
                                        },
                                        {
                                            xtype: 'filefield',
                                            anchor: '100%',
                                            fieldLabel: 'Key File',
                                            labelWidth: 130
                                        },
                                        {
                                            xtype: 'displayfield',
                                            anchor: '100%',
                                            padding: '0 0 0 135',
                                            labelWidth: 130,
                                            name: 'sshKeyFile'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    margin: '15 0 0 0',
                                    title: 'Static IP Address Settings (Optional)',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'IP Address',
                                            labelWidth: 130,
                                            name: 'ipAddress',
                                            vtype: 'numeric'
                                        },
                                        {
                                            xtype: 'textfield',
                                            validator: function(value) {
                                                return true;
                                            },
                                            anchor: '100%',
                                            fieldLabel: 'Net Mask',
                                            labelWidth: 130,
                                            name: 'netmask',
                                            vtype: 'numeric'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Gateway',
                                            labelWidth: 130,
                                            name: 'gateway',
                                            vtype: 'numeric'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Name Server',
                                            labelWidth: 130,
                                            name: 'nameServer',
                                            vtype: 'numeric'
                                        }
                                    ]
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            ui: 'footer',
                            layout: {
                                type: 'hbox',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        var instanceForm = Ext.getCmp("editInstanceForm");

                                        var machineId = instanceForm.getForm().findField("machineId").getValue();

                                        instanceForm.getForm().submit({
                                            clientValidation: true,
                                            url: GLOBAL.urlPrefix + "machine/updateMachine",
                                            params: {
                                                newStatus: 'delivered'
                                            },
                                            waitMsg: 'Saving Data...',
                                            success: function(form, action) {
                                                Ext.Msg.alert('Success', action.result.msg);

                                                Ext.getCmp('instancesGrid').getStore().load({

                                                    callback:function(records, operation, success){

                                                        Ext.each(records, function(record) {

                                                            if(record.get("machineId") == machineId) {
                                                                Ext.getCmp('instancesGrid').getSelectionModel().select(record,true,false);

                                                                instancesConstants.selectRow = record;
                                                                instancesConstants.me.selectInstanceGrid();
                                                            }
                                                        });
                                                    }

                                                });
                                                instanceForm.up('window').close();
                                            },
                                            failure: function(form, action) {

                                                switch (action.failureType) {
                                                    case Ext.form.action.Action.CLIENT_INVALID:
                                                    Ext.Msg.alert('Failure', '유효하지 않은 입력값이 존재합니다.');
                                                    break;
                                                    case Ext.form.action.Action.CONNECT_FAILURE:
                                                    Ext.Msg.alert('Failure', 'Server communication failed');
                                                    break;
                                                    case Ext.form.action.Action.SERVER_INVALID:
                                                    Ext.Msg.alert('Failure', action.result.msg);
                                                }
                                            }
                                        });

                                    },
                                    margin: '0 15 0 0',
                                    padding: '2 10 2 10',
                                    text: 'OK'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        Ext.MessageBox.confirm('Confirm', '작업을 취소하시겠습니까?', function(btn){

                                            if(btn == "yes"){
                                                button.up("window").close();
                                            }

                                        });

                                    },
                                    margin: '0 0 0 0',
                                    padding: '2 5 2 5',
                                    text: 'Cancel'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onRadiofieldChange: function(field, newValue, oldValue, eOpts) {

    }

});