/*
 * File: app/view/instancesContainer.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.instancesContainer', {
    extend: 'Ext.container.Container',
    alias: 'widget.instancesContainer',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.toolbar.Separator',
        'Ext.toolbar.TextItem',
        'Ext.button.Split',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.form.field.Text',
        'Ext.form.field.Hidden',
        'Ext.toolbar.Paging',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.Panel',
        'Ext.form.FieldContainer',
        'Ext.form.field.Checkbox',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.form.Label',
        'Ext.chart.Chart',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Line'
    ],

    height: 755,
    id: 'instancesContainer',
    itemId: 'instancesContainer',
    width: 1000,
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    region: 'center',
                    id: 'instancesGrid',
                    itemId: 'instancesGrid',
                    minHeight: 100,
                    autoScroll: true,
                    columnLines: true,
                    forceFit: true,
                    store: 'instanceListStore',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            id: 'instancesToolbar',
                            itemId: 'instancesToolbar',
                            width: 150,
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'newProjectWizardBtn',
                                    itemId: 'newProjectWizardBtn',
                                    text: 'New Project Wizard'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        var regInstanceWindow = Ext.create("widget.regInstanceWindow");

                                        regInstanceWindow.show();
                                    },
                                    id: 'createInstanceBtn',
                                    itemId: 'createInstanceBtn',
                                    text: 'Create Instance'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'tbtext',
                                    text: 'Filter : '
                                },
                                {
                                    xtype: 'splitbutton',
                                    id: 'categoryCycle',
                                    itemId: 'categoryCycle',
                                    text: 'All Categories',
                                    menu: {
                                        xtype: 'menu',
                                        id: 'categoryList',
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                id: 'allCategories',
                                                itemId: 'allCategories',
                                                text: 'All Categories'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                id: 'development',
                                                itemId: 'development',
                                                text: 'Development'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                id: 'production',
                                                itemId: 'production',
                                                text: 'Production'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'splitbutton',
                                    id: 'rhevmCycle',
                                    itemId: 'rhevmCycle',
                                    text: 'All RHEV Manager',
                                    menu: {
                                        xtype: 'menu',
                                        id: 'rhevmList',
                                        itemId: 'rhevmList',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                id: 'allRhevm',
                                                itemId: 'allRhevm',
                                                text: 'All RHEV Manager'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                id: 'rhevm1',
                                                itemId: 'rhevm1',
                                                text: 'RHEV-M1'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                id: 'rhevm2',
                                                itemId: 'rhevm2',
                                                text: 'RHEV-M2'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'searchInstanceName',
                                    itemId: 'searchInstanceName',
                                    fieldLabel: '',
                                    emptyText: 'Search Instance'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    id: 'searchCategory',
                                    itemId: 'searchCategory',
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    id: 'searchRhvm',
                                    itemId: 'searchRhvm',
                                    fieldLabel: 'Label'
                                }
                            ]
                        },
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'instanceListStore'
                        }
                    ],
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'instanceID',
                            text: 'InstanceID'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'instanceName',
                            text: 'InstanceName'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'category',
                            text: 'Category'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'rhevManager',
                            text: 'RhevManager'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'cluster',
                            text: 'Cluster'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'host',
                            text: 'Host'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'ipAddress',
                            text: 'IpAddress'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'agentStatus',
                            text: 'AgentStatus'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    region: 'south',
                    split: true,
                    id: 'instanceDetailPanel',
                    itemId: 'instanceDetailPanel',
                    items: [
                        {
                            xtype: 'tabpanel',
                            id: 'instanceTabPanel',
                            itemId: 'instanceTabPanel',
                            padding: '5 0 0 0',
                            activeTab: 0,
                            plain: true,
                            items: [
                                {
                                    xtype: 'panel',
                                    autoScroll: true,
                                    layout: 'fit',
                                    title: 'Description',
                                    items: [
                                        {
                                            xtype: 'form',
                                            id: 'instanceDescForm',
                                            itemId: 'instanceDescForm',
                                            defaults: {
                                                border: false,
                                                xtype: 'panel',
                                                flex: 1,
                                                layout: 'anchor'
                                            },
                                            bodyPadding: 10,
                                            bodyStyle: 'padding:5px 5px 0',
                                            header: false,
                                            fieldDefaults: {
                                                msgTarget: 'side',
                                                margin: '0 10',
                                                readOnly: true
                                            },
                                            waitMsgTarget: 'instDescForm',
                                            items: [
                                                {
                                                    xtype: 'fieldcontainer',
                                                    height: 34,
                                                    defaults: {
                                                        flex: 1
                                                    },
                                                    fieldLabel: 'Label',
                                                    hideLabel: true,
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'middle'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            fieldLabel: 'Instance ID'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            fieldLabel: 'Host'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'fieldcontainer',
                                                    height: 34,
                                                    defaults: {
                                                        flex: 1
                                                    },
                                                    fieldLabel: 'Label',
                                                    hideLabel: true,
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'middle'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            fieldLabel: 'OS Name'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            fieldLabel: 'OS Version'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'fieldcontainer',
                                                    height: 34,
                                                    defaults: {
                                                        flex: 1
                                                    },
                                                    fieldLabel: 'Label',
                                                    hideLabel: true,
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'middle'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            fieldLabel: 'MAC Address'
                                                        },
                                                        {
                                                            xtype: 'checkboxfield',
                                                            flex: 1,
                                                            fieldLabel: 'Is VM',
                                                            boxLabel: 'VM'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'fieldcontainer',
                                                    height: 34,
                                                    defaults: {
                                                        flex: 1
                                                    },
                                                    fieldLabel: 'Label',
                                                    hideLabel: true,
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'middle'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            fieldLabel: 'IP Address'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            fieldLabel: 'OS Arch'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'fieldcontainer',
                                                    height: 34,
                                                    defaults: {
                                                        flex: 1
                                                    },
                                                    fieldLabel: 'Label',
                                                    hideLabel: true,
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'middle'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            fieldLabel: 'CPU Clock'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            fieldLabel: 'Core'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'fieldcontainer',
                                                    height: 34,
                                                    defaults: {
                                                        flex: 1
                                                    },
                                                    fieldLabel: 'Label',
                                                    hideLabel: true,
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'middle'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            fieldLabel: 'Memory Size'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            fieldLabel: 'Create Date'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    autoScroll: true,
                                    layout: 'fit',
                                    title: 'Software',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            id: 'instanceSoftwareGrid',
                                            itemId: 'instanceSoftwareGrid',
                                            autoScroll: true,
                                            columnLines: true,
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'String'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'number',
                                                    text: 'Number'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    dataIndex: 'date',
                                                    text: 'Date'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Boolean'
                                                }
                                            ],
                                            dockedItems: [
                                                {
                                                    xtype: 'toolbar',
                                                    dock: 'top',
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            handler: function(button, e) {
                                                                var softwareInstallWindow = Ext.create("widget.softwareInstallWindow");

                                                                softwareInstallWindow.show();
                                                            },
                                                            id: 'softwareInstallBtn',
                                                            itemId: 'softwareInstallBtn',
                                                            text: 'Software Install'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    autoScroll: true,
                                    layout: 'fit',
                                    title: 'OS Package',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            id: 'instanceOsGrid',
                                            itemId: 'instanceOsGrid',
                                            autoScroll: true,
                                            columnLines: true,
                                            dockedItems: [
                                                {
                                                    xtype: 'toolbar',
                                                    dock: 'top',
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            id: 'osReloadBtn',
                                                            itemId: 'osReloadBtn',
                                                            text: 'Reload'
                                                        },
                                                        {
                                                            xtype: 'tbseparator'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            id: 'inputPackageName',
                                                            itemId: 'inputPackageName',
                                                            fieldLabel: 'Name',
                                                            labelWidth: 45,
                                                            emptyText: 'Search Package'
                                                        }
                                                    ]
                                                }
                                            ],
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'String'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'number',
                                                    text: 'Number'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    dataIndex: 'date',
                                                    text: 'Date'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Boolean'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    autoScroll: true,
                                    layout: 'fit',
                                    title: 'Monitoring',
                                    items: [
                                        {
                                            xtype: 'panel',
                                            height: 250,
                                            id: 'monitoringPanel',
                                            width: 400,
                                            layout: 'border',
                                            items: [
                                                {
                                                    xtype: 'panel',
                                                    flex: 1,
                                                    region: 'west',
                                                    id: 'cpuPanel',
                                                    width: 150,
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'stretch'
                                                    },
                                                    dockedItems: [
                                                        {
                                                            xtype: 'label',
                                                            dock: 'top',
                                                            cls: 'chart-title',
                                                            text: 'CPU'
                                                        }
                                                    ],
                                                    items: [
                                                        {
                                                            xtype: 'chart',
                                                            height: 250,
                                                            id: 'cpuChart',
                                                            itemId: 'cpuChart',
                                                            width: 400,
                                                            shadow: true,
                                                            animate: true,
                                                            insetPadding: 20,
                                                            store: 'tempChartData',
                                                            axes: [
                                                                {
                                                                    type: 'Category',
                                                                    fields: [
                                                                        'date'
                                                                    ],
                                                                    label: {
                                                                        rotate: {
                                                                            degrees: 315
                                                                        }
                                                                    },
                                                                    position: 'bottom'
                                                                },
                                                                {
                                                                    type: 'Numeric',
                                                                    fields: [
                                                                        'cpu'
                                                                    ],
                                                                    maximum: 100,
                                                                    position: 'left'
                                                                }
                                                            ],
                                                            series: [
                                                                {
                                                                    type: 'line',
                                                                    xField: 'x',
                                                                    yField: 'y',
                                                                    markerConfig: {
                                                                        radius: 3,
                                                                        size: 3
                                                                    },
                                                                    smooth: 3
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'panel',
                                                    flex: 1,
                                                    region: 'center',
                                                    id: 'cpuPanel1',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'stretch'
                                                    },
                                                    dockedItems: [
                                                        {
                                                            xtype: 'label',
                                                            dock: 'top',
                                                            cls: 'chart-title',
                                                            text: 'Memory'
                                                        }
                                                    ],
                                                    items: [
                                                        {
                                                            xtype: 'chart',
                                                            height: 250,
                                                            id: 'cpuChart1',
                                                            itemId: 'cpuChart',
                                                            width: 400,
                                                            shadow: true,
                                                            animate: true,
                                                            insetPadding: 20,
                                                            store: 'tempChartData',
                                                            axes: [
                                                                {
                                                                    type: 'Category',
                                                                    fields: [
                                                                        'date'
                                                                    ],
                                                                    label: {
                                                                        rotate: {
                                                                            degrees: 315
                                                                        }
                                                                    },
                                                                    position: 'bottom'
                                                                },
                                                                {
                                                                    type: 'Numeric',
                                                                    fields: [
                                                                        'cpu'
                                                                    ],
                                                                    maximum: 100,
                                                                    position: 'left'
                                                                }
                                                            ],
                                                            series: [
                                                                {
                                                                    type: 'line',
                                                                    xField: 'x',
                                                                    yField: 'y',
                                                                    markerConfig: {
                                                                        radius: 3,
                                                                        size: 3
                                                                    },
                                                                    smooth: 3
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'panel',
                                                    flex: 1,
                                                    region: 'east',
                                                    id: 'cpuPanel2',
                                                    width: 150,
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'stretch'
                                                    },
                                                    dockedItems: [
                                                        {
                                                            xtype: 'label',
                                                            dock: 'top',
                                                            cls: 'chart-title',
                                                            text: 'Disk'
                                                        }
                                                    ],
                                                    items: [
                                                        {
                                                            xtype: 'chart',
                                                            height: 250,
                                                            id: 'cpuChart2',
                                                            itemId: 'cpuChart',
                                                            width: 400,
                                                            shadow: true,
                                                            animate: true,
                                                            insetPadding: 20,
                                                            store: 'tempChartData',
                                                            axes: [
                                                                {
                                                                    type: 'Category',
                                                                    fields: [
                                                                        'date'
                                                                    ],
                                                                    label: {
                                                                        rotate: {
                                                                            degrees: 315
                                                                        }
                                                                    },
                                                                    position: 'bottom'
                                                                },
                                                                {
                                                                    type: 'Numeric',
                                                                    fields: [
                                                                        'cpu'
                                                                    ],
                                                                    maximum: 100,
                                                                    position: 'left'
                                                                }
                                                            ],
                                                            series: [
                                                                {
                                                                    type: 'line',
                                                                    xField: 'x',
                                                                    yField: 'y',
                                                                    markerConfig: {
                                                                        radius: 3,
                                                                        size: 3
                                                                    },
                                                                    smooth: 3
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});