/*
 * File: app/view/ManageAccountWindow.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ManageAccountWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.ManageAccountWindow',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.column.Action',
        'Ext.grid.View',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.panel.Tool'
    ],

    height: 400,
    id: 'manageAccountWindow',
    width: 300,
    resizable: false,
    layout: 'border',
    title: 'Manage Account',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    flex: 1,
                    region: 'center',
                    header: false,
                    title: 'ManageAccount',
                    items: [
                        {
                            xtype: 'gridpanel',
                            height: 358,
                            id: 'instanceAccountGrid',
                            itemId: 'instanceAccountGrid',
                            autoScroll: true,
                            columnLines: true,
                            forceFit: true,
                            store: 'AccountStore',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    dataIndex: 'machineId',
                                    hideable: false
                                },
                                {
                                    xtype: 'gridcolumn',
                                    minWidth: 150,
                                    dataIndex: 'account',
                                    text: 'Account ID'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    minWidth: 60,
                                    dataIndex: 'uid',
                                    text: 'UID'
                                },
                                {
                                    xtype: 'actioncolumn',
                                    text: 'Delete',
                                    maxWidth: 60,
                                    minWidth: 60,
                                    style: 'text-align:left;',
                                    width: 60,
                                    defaultWidth: 60,
                                    align: 'center',
                                    menuText: '',
                                    items: [
                                        {
                                            handler: function(view, rowIndex, colIndex, item, e, record, row) {

                                                if(record.get("uid") < 500) {
                                                    Ext.MessageBox.alert('Message', 'UID가 500 미만인 시스템 계정은 삭제할 수 없습니다.');
                                                    return;
                                                }

                                                Ext.MessageBox.confirm('Confirm', '삭제 하시겠습니까?', function(btn){

                                                    if(btn == "yes"){

                                                        Ext.Ajax.request({
                                                            url: GLOBAL.urlPrefix + "machine/removeAccount",
                                                            params : {
                                                                machineId : instancesConstants.actionRow.get("machineId"),
                                                                account : record.get("account"),
                                                                uid : record.get("uid")
                                                            },
                                                            disableCaching : true,
                                                            waitMsg: 'Delete Account...',
                                                            success: function(response){
                                                                var msg = Ext.JSON.decode(response.responseText).msg;
                                                                Ext.MessageBox.alert('알림', msg);

                                                                Ext.getCmp("instanceAccountGrid").getStore().reload();

                                                            }
                                                        });
                                                    }

                                                });
                                            },
                                            icon: 'resources/images/icons/delete.png',
                                            iconCls: ''
                                        }
                                    ]
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            handler: function(button, e) {
                                                var regAccountWindow = Ext.create("widget.RegAccountWindow");
                                                regAccountWindow.show();

                                                regAccountWindow.down("form").getForm().findField("machineId").setValue(instancesConstants.actionRow.get("machineId"));

                                                var groupStore = Ext.getStore("ComboGroupStore");
                                                groupStore.getProxy().extraParams = {
                                                    machineId : instancesConstants.actionRow.get("machineId")
                                                };
                                            },
                                            id: 'createAccountBtn',
                                            itemId: 'createAccountBtn',
                                            margin: '0 15 0 0',
                                            padding: '2 7 2 7',
                                            text: 'Create Account'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ],
            tools: [
                {
                    xtype: 'tool',
                    handler: function(event, toolEl, owner, tool) {
                        var accountStore = Ext.getCmp('instanceAccountGrid').getStore();

                        accountStore.getProxy().extraParams = {
                            machineId : instancesConstants.actionRow.get("machineId")
                        };

                        accountStore.load();

                    },
                    tooltip: '',
                    type: 'refresh'
                }
            ]
        });

        me.callParent(arguments);
    }

});