/*
 * File: app/view/PermissionUserWindow.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.PermissionUserWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.PermissionUserWindow',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.column.Action',
        'Ext.grid.View',
        'Ext.toolbar.Paging',
        'Ext.form.field.Text'
    ],

    height: 320,
    width: 580,
    resizable: false,
    title: 'Add Permission User',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    height: 275,
                    header: false,
                    title: 'My Grid Panel',
                    columnLines: true,
                    forceFit: true,
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            minWidth: 60,
                            dataIndex: 'string',
                            text: 'ID'
                        },
                        {
                            xtype: 'gridcolumn',
                            minWidth: 120,
                            dataIndex: 'number',
                            text: 'Login ID'
                        },
                        {
                            xtype: 'gridcolumn',
                            minWidth: 150,
                            dataIndex: 'date',
                            text: 'User Name'
                        },
                        {
                            xtype: 'gridcolumn',
                            minWidth: 150,
                            dataIndex: 'bool',
                            text: 'Dep Name'
                        },
                        {
                            xtype: 'actioncolumn',
                            text: 'Add',
                            maxWidth: 60,
                            minWidth: 70,
                            style: 'text-align:left;',
                            width: 60,
                            defaultWidth: 60,
                            align: 'center',
                            menuText: '',
                            items: [
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        alert('add');
                                    },
                                    icon: 'resources/images/icons/add.png',
                                    iconCls: ''
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true
                        },
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Filtering',
                                    labelWidth: 60,
                                    emptyText: 'Search User Name'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});