/*
 * File: app/view/softwareInstallWindow.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.softwareInstallWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.softwareInstallWindow',

    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Checkbox'
    ],

    height: 350,
    id: 'softwareInstallWindow',
    width: 500,
    layout: 'border',
    title: 'Software Install Launch Wizard',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    padding: '10 10 0 10',
                    items: [
                        {
                            xtype: 'combobox',
                            itemId: 'mycombobox2',
                            width: 350,
                            fieldLabel: 'Software',
                            queryMode: 'local',
                            store: [
                                'Apache HTTP Server',
                                'Apache Tomcat',
                                'JBoss EWS',
                                'JBoss EAP'
                            ]
                        }
                    ]
                },
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    ui: 'footer',
                    layout: {
                        type: 'hbox',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            id: 'installSofrwareBtn',
                            itemId: 'installSofrwareBtn',
                            margin: '0 15 0 0',
                            padding: '2 5 2 5',
                            text: 'Launch'
                        },
                        {
                            xtype: 'button',
                            id: 'installCancelBtn',
                            itemId: 'installCancelBtn',
                            margin: '0 0 0 0',
                            padding: '2 5 2 5',
                            text: 'Cancel'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'panel',
                    flex: 1,
                    region: 'center',
                    id: 'softwareInstallPanel',
                    itemId: 'softwareInstallPanel',
                    layout: 'card',
                    header: false,
                    title: 'sofrwareInstallPanel',
                    items: [
                        {
                            xtype: 'form',
                            height: 242,
                            id: 'apacheInstallForm',
                            itemId: 'apacheInstallForm',
                            autoScroll: true,
                            bodyPadding: 15,
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Apache HTTP Server Install',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            fieldLabel: 'Version',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Target Dir',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Server Root',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Port',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Server Domain',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            fieldLabel: 'Start Service',
                                            labelWidth: 110,
                                            boxLabel: 'Start Service after Installation'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            height: 242,
                            id: 'tomcatInstallForm',
                            itemId: 'tomcatInstallForm',
                            autoScroll: true,
                            bodyPadding: 15,
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Apache Tomcat Install',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            fieldLabel: 'Version',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Java Home',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Catalina Home',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Catalina Base',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Server Name',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Comp User',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Port Offset',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Heap Size',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Permgen Size',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            fieldLabel: 'Start Service',
                                            labelWidth: 110,
                                            boxLabel: 'Start Service after Installation'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            height: 242,
                            id: 'jbossEWSInstallForm',
                            itemId: 'jbossEWSInstallForm',
                            autoScroll: true,
                            bodyPadding: 15,
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'JBoss EWS Install',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            fieldLabel: 'Version',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Java Home',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Catalina Home',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Catalina Base',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Server Name',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Comp User',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Port Offset',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Heap Size',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Permgen Size',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            fieldLabel: 'High Availability',
                                            labelWidth: 110,
                                            boxLabel: 'Check when using clustering'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Multicast Address',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            fieldLabel: 'Start Service',
                                            labelWidth: 110,
                                            boxLabel: 'Start Service after Installation'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            height: 242,
                            id: 'jbossEAPInstallForm',
                            itemId: 'jbossEAPInstallForm',
                            autoScroll: true,
                            bodyPadding: 15,
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'JBoss EAP Install',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            fieldLabel: 'Version',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'JBoss Home',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Server Home',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Server Name',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Mgmt Address',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Bind Address',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Port Offset',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            fieldLabel: 'High Availability',
                                            labelWidth: 110,
                                            boxLabel: 'Use standalone-ha.xml'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Multicast Address',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Heap Size',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Permgen Size',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            fieldLabel: 'Start Service',
                                            labelWidth: 110,
                                            boxLabel: 'Start Service after Installation'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    title: '     Data Source Setting(Optional)',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            fieldLabel: 'Database Type',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'JNDI Name',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'JDBC URL',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'User Name',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Password',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Min Pool Size',
                                            labelWidth: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Max Pool Size',
                                            labelWidth: 110
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});