/*
 * File: app/view/storagePgContainer.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.storagePgContainer', {
    extend: 'Ext.container.Container',
    alias: 'widget.storagePgContainer',

    requires: [
        'Ext.grid.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.grid.View',
        'Ext.grid.column.Column'
    ],

    id: 'storagePgContainer',
    itemId: 'storagePgContainer',
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 2,
                    region: 'center',
                    id: 'storagePgGrid',
                    itemId: 'storagePgGrid',
                    columnLines: true,
                    forceFit: true,
                    store: 'storagePgJsonStore',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            height: 36,
                            id: 'storagePgToolbar',
                            itemId: 'storagePgToolbar'
                        }
                    ],
                    viewConfig: {
                        id: 'storagePgGridView',
                        itemId: 'storagePgGridView'
                    },
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'num',
                            text: 'Num'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'name',
                            text: 'Name'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'version',
                            text: 'Version'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'raw_bytes_used',
                            text: 'Raw_bytes_used'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'raw_bytes_avail',
                            text: 'Raw_bytes_avail'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 4,
                    region: 'south',
                    split: true,
                    id: 'storagePgDetail',
                    itemId: 'storagePgDetail',
                    autoScroll: true,
                    layout: 'border',
                    bodyPadding: 10,
                    bodyStyle: {
                        background: '#fff'
                    }
                }
            ]
        });

        me.callParent(arguments);
    }

});