/*
 * File: app/view/TemplateSummaryWindow.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.TemplateSummaryWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.TemplateSummaryWindow',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.RowNumberer',
        'Ext.grid.View'
    ],

    height: 480,
    width: 400,
    resizable: false,
    title: 'Template List',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    id: 'templateSummaryGrid',
                    itemId: 'templateSummaryGrid',
                    header: false,
                    title: 'My Grid Panel',
                    columnLines: true,
                    forceFit: true,
                    columns: [
                        {
                            xtype: 'rownumberer',
                            minWidth: 40,
                            width: 40
                        },
                        {
                            xtype: 'gridcolumn',
                            minWidth: 150,
                            dataIndex: 'field1',
                            text: 'Template Name'
                        },
                        {
                            xtype: 'gridcolumn',
                            minWidth: 100,
                            dataIndex: 'field2',
                            text: 'Description'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});