/*
 * File: app/view/userContainer.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.userContainer', {
    extend: 'Ext.container.Container',
    alias: 'widget.usercontainer',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.button.Cycle',
        'Ext.menu.Menu',
        'Ext.menu.CheckItem',
        'Ext.toolbar.Separator',
        'Ext.form.field.Text',
        'Ext.toolbar.Paging',
        'Ext.grid.column.Column',
        'Ext.form.Label',
        'Ext.form.Panel',
        'Ext.form.FieldContainer'
    ],

    height: 755,
    id: 'userContainer',
    itemId: 'userContainer',
    width: 1000,
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    region: 'center',
                    id: 'userGrid',
                    itemId: 'userGrid',
                    minHeight: 100,
                    autoScroll: true,
                    columnLines: true,
                    store: 'tempGridData',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            id: 'instancesToolbar1',
                            itemId: 'instancesToolbar',
                            width: 150,
                            items: [
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        var regInstanceWindow = Ext.create("widget.regInstanceWindow");

                                        regInstanceWindow.show();
                                    },
                                    id: 'createUserBtn',
                                    itemId: 'createUserBtn',
                                    text: 'Create New User'
                                },
                                {
                                    xtype: 'cycle',
                                    id: 'actionCycle',
                                    itemId: 'actionCycle',
                                    showText: true,
                                    menu: {
                                        xtype: 'menu',
                                        id: 'actionList',
                                        itemId: 'actionList',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menucheckitem',
                                                id: 'actions',
                                                itemId: 'actions',
                                                text: 'Actions'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'inputUserName',
                                    itemId: 'inputUserName',
                                    fieldLabel: 'Filtering',
                                    labelWidth: 60,
                                    emptyText: 'Search User Name'
                                }
                            ]
                        },
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true
                        }
                    ],
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'id',
                            text: 'Id'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    region: 'south',
                    split: true,
                    id: 'userDetailPanel',
                    itemId: 'userDetailPanel',
                    items: [
                        {
                            xtype: 'label',
                            html: '<h2>&nbsp;&nbsp;Administrator</h2>',
                            margin: '',
                            padding: '0 10 0 0',
                            text: ''
                        },
                        {
                            xtype: 'form',
                            id: 'userForm',
                            itemId: 'userForm',
                            padding: '',
                            defaults: {
                                border: false,
                                xtype: 'panel',
                                flex: 1,
                                layout: 'anchor'
                            },
                            bodyPadding: 10,
                            bodyStyle: 'padding:5px 5px 0',
                            header: false,
                            fieldDefaults: {
                                msgTarget: 'side',
                                margin: '0 10',
                                readOnly: true
                            },
                            waitMsgTarget: 'instDescForm',
                            items: [
                                {
                                    xtype: 'fieldcontainer',
                                    height: 34,
                                    defaults: {
                                        flex: 1
                                    },
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'User ID'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Dept Name'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    height: 34,
                                    defaults: {
                                        flex: 1
                                    },
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Role ID'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Email'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    height: 34,
                                    defaults: {
                                        flex: 1
                                    },
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Login ID'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Is Admin'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    height: 34,
                                    defaults: {
                                        flex: 1
                                    },
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Password'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Status'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    height: 34,
                                    defaults: {
                                        flex: 1
                                    },
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'User Name'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Last Logon'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});